FROM tomcat:9.0.90-jre17
RUN useradd -ms /bin/bash tomcatuser
WORKDIR /home/tomcatuser
COPY ctlms.war /usr/local/tomcat/webapps/
RUN chown -R tomcatuser:tomcatuser /usr/local/tomcat/webapps
USER tomcatuser
EXPOSE 8080
