cat << EOF >>./init.sql
CREATE ROLE 'webapp_users';
GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE,ALTER,CREATE,DROP,INDEX ON ctlms.* TO 'webapp_users';
CREATE USER "${CTLMS_DB_USER}" IDENTIFIED BY "${CTLMS_DB_PASSWORD}" DEFAULT ROLE 'webapp_users';
EOF